credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              id: "7ab18af1-e683-402e-b1a6-d61d09a5650b"
              password: ${casc-secret/test}
              scope: GLOBAL
              username: "test-user"

jenkins:
  systemMessage: "Controlled by Configuration as Code. Do not install plugins manually, read: https://docs.engineering.redhat.com/pages/viewpage.action?pageId=93546799"
  numExecutors: 1
  quietPeriod: 0

  # Default LDAP configuration
  securityRealm:
    ldap:
      cache:
        size: 100
        ttl: 10
      configurations:
        - server: ldaps://ldap.corp.redhat.com
          rootDN: dc=redhat,dc=com
          displayNameAttributeName: cn
          inhibitInferRootDN: false
          userSearch: uid={0}
          groupSearchBase: ou=adhoc,ou=managedGroups
          groupSearchFilter: (& (cn={0}) (objectclass=GroupOfUniqueNames))
      userIdStrategy: CaseInsensitive
      groupIdStrategy: CaseInsensitive
      disableRolePrefixing: true

  # Markup Formatter
  markupFormatter:
    rawHtml:
      disableSyntaxHighlighting: false

  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Jenkins administrators"
            permissions:
              - "Overall/Administer"
            assignments:
              - "cci-octopus" # Instance telemetry collection
              - "ci-support" # Access for the support team
              - "sysops" # Access for the support team
              - "ccit-test" # OpenShift automation account
              - "ccit" # CCIT team
              - "windup-eng"
              # Here put customer's Rover group
          - name: "anonymous"
            description: "Anonymous users"
            permissions:
              - "Overall/Read"
              - "Job/Read"
            assignments:
              - "anonymous"
          - name: "readonly"
            description: "Read-only users"
            permissions:
              - "Overall/Read"
              - "Job/Read"
              - "Job/ExtendedRead"
              - "View/Read"
            assignments:
              - "authenticated"

  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"

  updateCenter:
    sites:
    - id: "default"
      url: "https://2-235-jenkins-csb-uc.cloud.paas.psi.redhat.com/update-center.json"

security:
  sSHD:
    port: 50022
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true

unclassified:
  shell:
    shell: "bash"

configuration-as-code:
  deprecated: warn

jobs:
  - url: https://gitlab.cee.redhat.com/ccit/monitoring-seed/raw/master/seed.groovy
